[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://remidefleurian.com/"
  to = "https://remidefleurian.com/about"
  status = 301
  force = true

[[redirects]]
  from = "https://remidefleurian.com/linkedin"
  to = "https://www.linkedin.com/in/remidefleurian/"
  status = 301
  force = true

 [[redirects]]
  from = "https://remidefleurian.com/github"
  to = "https://github.com/remidefleurian/"
  status = 301
  force = true

[[redirects]]
  from = "https://remidefleurian.com/scholar"
  to = "https://scholar.google.co.uk/citations?user=kH6xaHsAAAAJ"
  status = 301
  force = true

[[redirects]]
  from = "https://remidefleurian.com/osf"
  to = "https://osf.io/f2jgd/"
  status = 301
  force = true